package com.kotlin.project.data.model.failure

object Failure {
    const val message = "エラーが発生しました。再度お試しください。"
}
